name: thingaha
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_fonts: ^2.0.0
  carousel_slider: ^2.3.3
  shared_preferences: ^2.0.5
  flutter_riverpod: ^0.14.0+3
  circle_flags: ^0.0.2
  collection: ^1.15.0
  md2_tab_indicator: ^1.0.2
  intl: ^0.17.0
  flutter_svg: ^0.22.0
  loading_indicator: ^2.0.1
  flutter_sticky_header: ^0.6.0
  sticky_headers: ^0.2.0
  eva_icons_flutter: ^3.0.0
  modal_bottom_sheet: ^2.0.0
  fl_chart: ^0.36.1
  easy_localization: ^3.0.0
  localization: ^0.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
   - images/
   - assets/translations/

  fonts:
    - family: Tagu
      fonts:
        - asset: fonts/Tagu.ttf
    - family: Sanpya
      fonts:
        - asset: fonts/Sanpya.ttf
